doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                #configure these for you database server
                url: '%env(resolve:DATABASE_URL)%'
                driver: 'pdo_pgsql'
                server_version: '13'
                charset: utf8
                mapping_types:
                    name: string
            order:
                #configure these for you database server
                url: '%env(resolve:DATABASE_LOCAL_URL)%'
                driver: 'pdo_mysql'
                server_version: '10.3'
                charset: utf8

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        default_entity_manager: default
        auto_generate_proxy_classes: true
        entity_managers:
            default:
                connection: default
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                auto_mapping: true
                mappings:
                    Main:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Main'
                        prefix: 'App\Entity\Main'
                        alias: Main
            order:
                connection: order
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                mappings:
                    Order:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Order'
                        prefix: 'App\Entity\Order'
                        alias: Order
